# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build-cli
      - task: build-container

  build-cli:
    dir: cli
    cmds:
      - docker build -t smcr/secman-cli .
      - docker push smcr/secman-cli

  build-container:
    dir: container
    cmds:
      - docker build -t smcr/secman .
      - docker push smcr/secman
