name: Secman Docker Image CI (VM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECMAN_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/secman:vm

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  run:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Run the Docker image
        uses: actions/checkout@v2
      - run: |
          CID=$(docker create -t -i ${{ secrets.DOCKER_ID }}/secman:vm)
          docker start -a -i $CID
